engines:
  duplication:
    enabled: true
    exclude_fingerprints:
    - facc28b6b813325fdfc12ee045478a97
    - 32b67e417a51f52071bbc97a9f04cd34
    - ca4e90b0ae4809a5d008452a4e7cc5e3
    config:
      languages:
        python:
          mass_threshold: 34
  pep8:
    enabled: true
  fixme:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
   - "**.py"
exclude_paths:
  - "implementation/primaries/**/tests/"
