# Taken from: https://packaging.python.org/en/latest/appveyor.html
# and from: https://bitbucket.org/pygame/pygame/pull-request/45/create-python-wheel-builds-using-appveyor/diff
# For now considering only Python 2.7, looking to support soon Python 2.6
# and Python 3 in the future

environment:
  MSCORE:
    secure: MahnjRB7MFd2KSyEeQtyqOZ9igP42L56lqgQ4caSlpPjLl294pAIj27bPI6WzRuX

  matrix:
    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3.5"
      PYTHON_ARCH: "32"
      DISTRIBUTIONS: "bdist_wheel"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.1"
      PYTHON_ARCH: "32"
      DISTRIBUTIONS: "bdist_wheel"

    - PYTHON: "C:\\Python33-x64"
      PYTHON_VERSION: "3.3.5"
      PYTHON_ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.1"
      DISTRIBUTIONS: "bdist_wheel"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.1"
      PYTHON_ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.1"
      DISTRIBUTIONS: "bdist_wheel"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - ps: Start-FileDownload 'http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.4/PyQt4-4.11.4-gpl-Py3.4-Qt4.8.7-x64.exe' -FileName pyqt4_installer.exe -Timeout 600000
  - cmd: pyqt4_installer.exe /S
  - cmd: python -c "import PyQt4"
  
  - "set PATH=%PATH%;%PYTHON%;%PYTHON%\\Scripts"
  - "pip install nose"
  - "pip install -r requirements.txt"
  - "set HOME=%APPVEYOR_BUILD_FOLDER%"

build: off

test_script:
  - "nosetests --logging-level=WARNING"


