environment:
  MSCORE:
    secure: MahnjRB7MFd2KSyEeQtyqOZ9igP42L56lqgQ4caSlpPjLl294pAIj27bPI6WzRuX
    
  matrix:
    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.3"
      PYTHON_ARCH: "32"

platform: x86

configuration: Release

init:
  - cmd: ECHO Processor architecture - %PROCESSOR_ARCHITECTURE%
  - cmd: wmic OS get OSArchitecture

  # As AppVeyor has multiple python install, verify which one uses by default
  - cmd: ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
  - cmd: python --version
  - cmd: python -c "import struct; print(struct.calcsize('P') * 8)"

  # Set the relevant python and pip location to the path
  - cmd: set PATH=%PYTHON%;%PYTHON%\scripts;%PATH%
  - cmd: ECHO Path - %PATH%

  # Verify the new default python
  - cmd: python --version
  - cmd: python -c "import struct; print(struct.calcsize('P') * 8)"
  - cmd: pip --version

  # Check out installed python packages
  - cmd: pip freeze

install:
  # Temporary fix for PyQt not being installed in correct directory: https://github.com/appveyor/ci/issues/363
  - REG ADD HKCU\Software\Python\PythonCore\3.4\InstallPath /f /ve /t REG_SZ /d C:\Python34

  # Download PyQt5 with 10min timeout, rename to pyqt5_installer.exe, and install
  - ps: Start-FileDownload 'http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.4/PyQt4-4.11.4-gpl-Py3.4-Qt4.8.7-x32.exe' -FileName pyqt4_installer.exe -Timeout 600000
  - cmd: pyqt4_installer.exe /S
  - cmd: python -c "import PyQt4"
  
  - cmd: pip install -r requirements.txt

  # Check installed packages again
  - cmd: pip freeze
  - cmd: cd music-library

build: off

test_script:
# temporary measure: disable online tests because the results vary
  - py.test --cov-report xml:.coverage
  - codeclimate-test-reporter


